### Numpy Exercises

In [1]:
import numpy as np

In [9]:
# 1-d or 2-d?
x = np.array([1, 2, 3])
print(x.ndim, x.shape)
y = np.array([[1], [2], [3]])
print(y.ndim, y.shape)

1 (3,)
2 (3, 1)


In [6]:
# reshape
arr2d = np.arange(1, 7).reshape(2, 3)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# an arithmetic operation
arr2d * arr2d

array([[ 1,  4,  9],
       [16, 25, 36]])

In [7]:
# basic indexing and slicing
print(arr2d[1, 2])
print(arr2d[1])
print(arr2d[:, 1])
print(arr2d[:1, 1:])

6
[4 5 6]
[2 5]
[[2 3]]


In [10]:
# a view or a copy?
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[:] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [12]:
# Boolean indexing
arr2d = np.arange(12).reshape((3, 4))
names = np.array(['Bob', 'Joe', 'Tom'])
arr2d[names != 'Joe']

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [17]:
arr2d = np.arange(12).reshape((3, 4))
arr2d


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
# fancy indexing
print(arr2d[[2, 1, 0, 1]])
row = np.arange(arr2d.shape[0])
col = np.array([1, 2, 0])
print(arr2d[row, col])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]
 [ 4  5  6  7]]
[1 6 8]


In [14]:
# ufuncs
arr = np.arange(1, 11)
(arr - np.mean(arr)) / np.std(arr)

array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
        0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ])

In [15]:
# aggregation
arr2d = np.arange(1, 7).reshape((2, 3))
np.sum(arr2d, axis = 1)

array([ 6, 15])

In [16]:
arr2d = np.arange(1, 7).reshape((2, 3))
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# high dimensional
arr3d = np.arange(24).reshape((2, 3, 4))
np.sum(arr3d, axis = 1)

In [18]:
def foo(astr, n):

while n > 0:

    print(astr, end = '')

    n -= 1

k = 4

foo('b', k)

print(k, end='')

IndentationError: expected an indented block (<ipython-input-18-3e8711c1f31f>, line 3)

In [20]:
import numpy as np
arr = np.linspace(-5, 5, 11, dtype = int)
arr[arr < 0] = 0
arr

array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5])

In [11]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

x[:,2]


array([ 3,  7, 11])

In [12]:
x = np.arange(3, 10, 2)

y = 3 + x

y[2]

10

In [13]:
arr = np.linspace(-2, 2, 5, dtype = int)

arr[-1]

2

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a.shape[1]

3

In [15]:
a = np.linspace(0, 3, 7)

b = np.linspace(2, 8, 7)

(a + b)[1]

3.5

In [17]:
arr = np.linspace(-5, 5, 11, dtype = int)

arr[arr < 0] = 0
arr

array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5])

In [23]:
a *= 2

print(a)

return a

 

a = 5

a = 1

a




[  0.  32.  64.  96. 128. 160. 192.]


SyntaxError: 'return' outside function (<ipython-input-23-3579964e6b1e>, line 5)

In [24]:
a *= 2

print(a)

return a

 

a = 5

a = 1

a

[  0.  64. 128. 192. 256. 320. 384.]


SyntaxError: 'return' outside function (<ipython-input-24-bb54b051ed68>, line 5)

In [21]:
def foo(astr, n):

    while n > 0:

        print(astr, end = '')
        n -= 1   
        k = 4
        foo('b', k)
    print(k, end = '')