### Numpy Exercises

In [ ]:
import numpy as np

In [ ]:
# 1-d or 2-d?
x = np.array([1, 2, 3])
print(x.ndim, x.shape)
y = np.array([[1], [2], [3]])
print(y.ndim, y.shape)

In [ ]:
# reshape
arr2d = np.arange(1, 7).reshape(2, 3)

In [ ]:
# an arithmetic operation
arr2d * arr2d

In [ ]:
# basic indexing and slicing
print(arr2d[1, 2])
print(arr2d[1])
print(arr2d[:, 1])
print(arr2d[:1, 1:])

In [ ]:
# a view or a copy?
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[:] = 12
arr

In [ ]:
# Boolean indexing
arr2d = np.arange(12).reshape((3, 4))
names = np.array(['Bob', 'Joe', 'Tom'])
arr2d[names != 'Joe']

In [ ]:
# fancy indexing
print(arr2d[[2, 1, 0, 1]])
row = np.arange(arr2d.shape[0])
col = np.array([1, 2, 0])
print(arr2d[row, col])

In [ ]:
# ufuncs
arr = np.arange(1, 11)
(arr - np.mean(arr)) / np.std(arr)

In [ ]:
# aggregation
arr2d = np.arange(1, 7).reshape((2, 3))
np.sum(arr2d, axis = 1)

In [ ]:
# high dimensional
arr3d = np.arange(24).reshape((2, 3, 4))
np.sum(arr3d, axis = 1)

In [3]:
def foo(astr, n):

while n > 0:

    print(astr, end = '')

    n -= 1

k = 4

foo('b', k)

print(k, end='')

IndentationError: expected an indented block (<ipython-input-3-3e8711c1f31f>, line 3)

In [9]:
import numpy as np
arr = np.linspace(-5, 5, 11, dtype = int)
arr[arr < 0] = 0

In [11]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

x[:,2]


array([ 3,  7, 11])

In [12]:
x = np.arange(3, 10, 2)

y = 3 + x

y[2]

10

In [13]:
arr = np.linspace(-2, 2, 5, dtype = int)

arr[-1]

2

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a.shape[1]

3

In [15]:
a = np.linspace(0, 3, 7)

b = np.linspace(2, 8, 7)

(a + b)[1]

3.5

In [17]:
arr = np.linspace(-5, 5, 11, dtype = int)

arr[arr < 0] = 0
arr

array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5])

In [23]:
a *= 2

print(a)

return a

 

a = 5

a = 1

a




[  0.  32.  64.  96. 128. 160. 192.]


SyntaxError: 'return' outside function (<ipython-input-23-3579964e6b1e>, line 5)

In [24]:
a *= 2

print(a)

return a

 

a = 5

a = 1

a

[  0.  64. 128. 192. 256. 320. 384.]


SyntaxError: 'return' outside function (<ipython-input-24-bb54b051ed68>, line 5)

In [36]:
def foo(astr, n):

    while n > 0:

        print(astr, end = '')
        n -= 1   
        k = 4
        foo('b', k)
    print(k, end = '')